DROP TABLE IF EXISTS product_to_category;
DROP TABLE IF EXISTS store_to_category;
DROP TABLE IF EXISTS product_category;
DROP TABLE IF EXISTS store_category;
DROP TABLE IF EXISTS image_to_store;
DROP TABLE IF EXISTS image_to_product;
DROP TABLE IF EXISTS images;
DROP TABLE IF EXISTS store;
DROP TABLE IF EXISTS product;
